DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS name;

CREATE TABLE cards (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	front TEXT NOT NULL,
	back TEXT NOT NULL,
	name_id TEXT
);

CREATE TABLE name (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL
);
